//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCIv3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OdyClerkInternalEntities : DbContext
    {
        public OdyClerkInternalEntities()
            : base("name=OdyClerkInternalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TCIv3_AgencyVendorInfo> TCIv3_AgencyVendorInfo { get; set; }
    
        public virtual ObjectResult<TCIv3_GetAgencyInfo_Result> TCIv3_GetAgencyInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TCIv3_GetAgencyInfo_Result>("TCIv3_GetAgencyInfo");
        }
    }
}
